### ISSUE TITLE
Missing reusable boxes hook

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-element-trash-drupal#5]
@mkernel 
I couldn't find a hook_grid_reusable_boxes_alter(...) 

This one would be very important for the "delete reusable Boxes" function

**Comment by mkernel** [comment]
There is none and there'll never be one. And the reason is simple: reusable boxes are not a special "citizen" - they're regular boxes and they're presented to the user through the normal "search" workflow. Hence you have to implement the reuse trash the same way you do in the other cases.

This is a won't-fix.
